### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Heimdell** [bennofs/th-lift-instances#11] opened 2018-01-22 13:58 UTC
I get this error:
```
[1 of 1] Compiling Instances.TH.Lift ( src/Instances/TH/Lift.hs, dist/build/Instances/TH/Lift.o )

src/Instances/TH/Lift.hs:137:1: error:
    • No instance for (Lift a) arising from a use of ‘lift’
      Possible fix:
        add (Lift a) to the context of the instance declaration
    • In the second argument of ‘Language.Haskell.TH.Lib.appE’, namely
        ‘lift x0_adBt’
      In the first argument of ‘Language.Haskell.TH.Lib.appE’, namely
        ‘Language.Haskell.TH.Lib.appE
           (Language.Haskell.TH.Lib.conE
              (Language.Haskell.TH.Syntax.Name
                 (Language.Haskell.TH.Syntax.mkOccName "Node")
                 (Language.Haskell.TH.Syntax.NameG
                    Language.Haskell.TH.Syntax.DataName
                    (Language.Haskell.TH.Syntax.mkPkgName "containers-0.5.7.1")
                    (Language.Haskell.TH.Syntax.mkModName "Data.Tree"))))
           (lift x0_adBt)’
      In the expression:
        Language.Haskell.TH.Lib.appE
          (Language.Haskell.TH.Lib.appE
             (Language.Haskell.TH.Lib.conE
                (Language.Haskell.TH.Syntax.Name
                   (Language.Haskell.TH.Syntax.mkOccName "Node")
                   (Language.Haskell.TH.Syntax.NameG
                      Language.Haskell.TH.Syntax.DataName
                      (Language.Haskell.TH.Syntax.mkPkgName "containers-0.5.7.1")
                      (Language.Haskell.TH.Syntax.mkModName "Data.Tree"))))
             (lift x0_adBt))
          (lift x1_adBu)
```

I use GHC-8.0.1.

**Comment by bennofs** [comment] 2018-01-22 15:13
Duplicate of #10

**Closed as completed** 2018-01-22 15:15 UTC
